name = "cloudflare_cable"
main = "src/index.ts"
# Must be >= 2026-02-24 so that calling deleteAll() cleans up underlying Alarms automatically
compatibility_date = "2026-05-26"

routes = [
  { pattern = "cable.yourdomain.com/cable/custom/*", zone_name = "yourdomain.com" },
  { pattern = "cable.yourdomain.com/cable/connect/*", zone_name = "yourdomain.com" },
  { pattern = "cable.yourdomain.com/cable/contact/*", zone_name = "yourdomain.com" } 
]

[[durable_objects.bindings]]
name = "TUNNEL_ROOM"
class_name = "TunnelRoom"

[[migrations]]
tag = "v2"
# Enable SQLite storage backend support to significantly boost sync and R/W performance
new_sqlite_classes = ["TunnelRoom"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[placement]
mode = "smart"

[observability.traces]
enabled = true